stages:
  - deploy

deploy_strato:
  stage: deploy
  image: alpine:3.22

  before_script:
    - apk add --no-cache lftp

  script:
    - |
      lftp -u "$STRATO_SFTP_USER","$STRATO_SFTP_PASSWORD" \
        "sftp://$STRATO_SFTP_HOST:$STRATO_SFTP_PORT" <<EOF
      set net:max-retries 2
      set net:timeout 30

      mirror --reverse --verbose \
        --exclude-glob=".git/" \
        --exclude-glob=".git/**" \
        --exclude-glob=".gitlab-ci.yml" \
        ./ "$STRATO_REMOTE_PATH"

      bye
      EOF

  environment:
    name: production
    url: https://www.pepijnvos.com

  resource_group: strato-production

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'